name: github-action-file
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        uses: actions/checkout@v4
      - name: third party
        run: cowsay -f dragon "Run for Cover, I am a Dragon...RAWR" >> dragon.txt
      - name: step2
        run: |
          echo "my second job step2"
          ls 
          cat README.md
